"""Tests for `docfleet index` and the deterministic index generator."""

from __future__ import annotations

from pathlib import Path

import pytest

from docfleet.indexer import generate
from tests.conftest import run, run_json, write_doc

EXPECTED = """\
# Fleet index

<!-- generated by `docfleet index`; edits are overwritten -->

## machines/laptop

- [notes/](machines/laptop/docs/notes)
- [plan.md](machines/laptop/docs/plan.md)

## machines/desktop

_empty_

## shared

- [commands/](shared/commands)
- [standards/](shared/standards)
"""


def two_machines(laptop: Path) -> Path:
    """Add a second machine and some documents to a fleet."""
    assert run("init", "--join", str(laptop), "--machine", "desktop") == 0
    write_doc(laptop, "machines/laptop/docs/plan.md")
    (laptop / "machines/laptop/docs/notes").mkdir()
    return laptop


def test_index_matches_the_expected_document(laptop: Path) -> None:
    repo = two_machines(laptop)
    assert generate(repo) == EXPECTED


def test_index_writes_the_file_and_reports_its_status(
    laptop: Path, capsys: pytest.CaptureFixture
) -> None:
    repo = two_machines(laptop)
    code, payload = run_json(capsys, "index", "--repo", str(repo))
    assert code == 0
    assert payload["status"] == "written"
    assert (repo / "INDEX.md").read_text(encoding="utf-8") == EXPECTED

    assert run("index", "--repo", str(repo)) == 0
    assert "unchanged: " in capsys.readouterr().out


def test_index_is_deterministic(laptop: Path) -> None:
    repo = two_machines(laptop)
    assert generate(repo) == generate(repo)


def test_index_skips_placeholder_and_hidden_files(laptop: Path) -> None:
    write_doc(laptop, "machines/laptop/docs/.hidden.md")
    assert ".hidden" not in generate(laptop)
    assert ".gitkeep" not in generate(laptop)
