"""Generate `INDEX.md`, the table of contents of a fleet repository.

The index lists, for every registered machine (in `fleet.json` order), the top
level of its `docs/` folder, then the top level of `shared/`. Output is fully
deterministic -- sorted entries, no timestamps -- so `docfleet doctor` can
detect a stale index by comparing the file against a fresh :func:`generate`.
"""

from __future__ import annotations

from pathlib import Path

from .layout import (
    INDEX_FILE,
    KEEP_FILE,
    MACHINES_DIR,
    SHARED_DIR,
    machine_names,
    read_fleet,
)

INDEX_TITLE = "# Fleet index"
INDEX_NOTE = "<!-- generated by `docfleet index`; edits are overwritten -->"
EMPTY_NOTE = "_empty_"
DOCS_DIR = "docs"


def index_path(repo: Path) -> Path:
    """Return the path of the generated index."""
    return repo / INDEX_FILE


def _visible(directory: Path) -> list[Path]:
    if not directory.is_dir():
        return []
    entries = [
        entry
        for entry in directory.iterdir()
        if entry.name != KEEP_FILE and not entry.name.startswith(".")
    ]
    return sorted(entries, key=lambda entry: entry.name)


def _entry_line(entry: Path, prefix: str) -> str:
    suffix = "/" if entry.is_dir() else ""
    return f"- [{entry.name}{suffix}]({prefix}/{entry.name})"


def _section(title: str, directory: Path, prefix: str) -> list[str]:
    lines = [f"## {title}", ""]
    entries = _visible(directory)
    lines.extend(_entry_line(entry, prefix) for entry in entries)
    if not entries:
        lines.append(EMPTY_NOTE)
    lines.append("")
    return lines


def generate(repo: Path) -> str:
    """Return the index content for `repo` without touching the filesystem."""
    lines = [INDEX_TITLE, "", INDEX_NOTE, ""]
    for name in machine_names(read_fleet(repo)):
        prefix = f"{MACHINES_DIR}/{name}/{DOCS_DIR}"
        lines.extend(_section(f"{MACHINES_DIR}/{name}", repo / prefix, prefix))
    lines.extend(_section(SHARED_DIR, repo / SHARED_DIR, SHARED_DIR))
    return "\n".join(lines).rstrip("\n") + "\n"


def is_stale(repo: Path) -> bool:
    """Return True when the index is missing or no longer matches the layout."""
    path = index_path(repo)
    if not path.is_file():
        return True
    return path.read_text(encoding="utf-8") != generate(repo)


def write_index(repo: Path) -> bool:
    """Write the index when it differs. Returns True when the file changed."""
    path = index_path(repo)
    content = generate(repo)
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def run_index(repo: Path) -> dict:
    """Run `docfleet index`. Returns a result document."""
    changed = write_index(repo)
    return {
        "command": "index",
        "repo": str(repo),
        "path": str(index_path(repo)),
        "status": "written" if changed else "unchanged",
        "exit_code": 0,
    }
